In [2]:
import numpy as np

In [8]:
x = [1, 2.3, 52.5, 34]

a=np.array(x)
print(a)

[ 1.   2.3 52.5 34. ]


In [11]:
print(a-10)

[-9.  -7.7 42.5 24. ]


In [15]:
y=np.arange(2,20,2)
print(y)

[ 2  4  6  8 10 12 14 16 18]


In [28]:
z=np.arange(10.100)
w=np.arange(0.1,1.2,0.15)
print(z)
print(w)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0.1  0.25 0.4  0.55 0.7  0.85 1.   1.15]


In [38]:
# Numpy arrays

a=np.array([1,2,3,4])
b=np.array([[1,1],[2,2]])

print(a)
print (a.ndim)
print("\n")

print(b)
print (b.ndim)

np.shape(a)
np.shape(b)

[1 2 3 4]
1


[[1 1]
 [2 2]]
2


(2, 2)

In [43]:
#indexing

print(b[0])

print(b[0,0])

[1 1]
1


In [45]:
a=np.random.randn(6,4)
print(a)

[[-1.20764005 -0.28989232  0.58455771 -1.33909266]
 [-1.04782646  0.40797554  1.05863054  0.72924364]
 [ 1.18850991  0.06050481  0.66152934  0.56442067]
 [ 2.7011069   1.75896571  0.44946274  0.55733937]
 [ 0.38357263  2.15043432 -0.39485808  0.99773164]
 [-0.08708976  0.49836123 -0.59209813  0.8555454 ]]
