In [1]:
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [2]:
seperator = r"\t"
df = pd.read_csv("textcv.csv",sep=seperator,names=['Status','Message'])
df.head()

<ipython-input-2-d111af367069>:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv("textcv.csv",sep=seperator,names=['Status','Message'])


Status                                            Message
0   "ham  Go until jurong point", crazy.. Available only...
1   "ham        Ok lar... Joking wif u oni...",,,,,,,,,,,,,
2  "spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   "ham  U dun say so early hor... U c already then say...
4   "ham  Nah I don't think he goes to usf", he lives ar...

In [3]:
len(df)

5574

In [4]:
len(df[df.Status=='"spam'])

747

In [5]:
len(df[df.Status=='"ham'])

4827

In [6]:
#CHANGING SPAM AND HAM to 0 and 1
df.loc[df["Status"]=='"ham',"Status",]=1
df.loc[df["Status"]=='"spam',"Status",]=0
df.head()

Status                                            Message
0      1  Go until jurong point", crazy.. Available only...
1      1        Ok lar... Joking wif u oni...",,,,,,,,,,,,,
2      0  Free entry in 2 a wkly comp to win FA Cup fina...
3      1  U dun say so early hor... U c already then say...
4      1  Nah I don't think he goes to usf", he lives ar...

In [7]:
df_x=df["Message"]
df_y=df["Status"]

In [8]:
#deauture_extraction text
cv = CountVectorizer()
#SPLIT TRAINING AND TEST DATA
x_train, x_test, y_train, y_test = train_test_split(df_x, df_y, test_size=0.2, random_state=4)
x_train.head()

5315    My sister going to earn more than me da.",,,,,...
2082    I'm aight. Wat's happening on your side.",,,,,...
1072    URGENT! We are trying to contact U. Todays dra...
1296              TELL HER I SAID EAT SHIT.",,,,,,,,,,,,,
472     How long has it been since you screamed", prin...
Name: Message, dtype: object

In [9]:
#CV TRANSFORM (ONLY TESTING)
x_traincv = cv.fit_transform(["Hi How are you How are you doing","Hi what's up","Wow that's awesome"])
#EXTRACTING FEAUTURES FROM THE WORDS ABOVE
x_traincv.toarray()

array([[2, 0, 1, 1, 2, 0, 0, 0, 0, 2],
       [0, 0, 0, 1, 0, 0, 1, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 1, 0]], dtype=int64)

In [10]:
cv.get_feature_names()

['are', 'awesome', 'doing', 'hi', 'how', 'that', 'up', 'what', 'wow', 'you']

In [11]:
#CV TRANSFORM TRAINING DATA (REAL)
x_traincv=cv.fit_transform(x_train)
#EXTRACTING FEAUTURES FROM X_TRAIN
a=x_traincv.toarray()

In [12]:
a[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [13]:
cv.inverse_transform(a[0])

[array(['da', 'earn', 'going', 'me', 'more', 'my', 'sister', 'than', 'to'],
       dtype='<U32')]

In [14]:
x_train.iloc[0]

'My sister going to earn more than me da.",,,,,,,,,,,,,'

In [15]:
#CV TRANSFORM TEST DATA (REAL)
x_testcv=cv.transform(x_test)
x_testcv

<1115x7759 sparse matrix of type '<class 'numpy.int64'>'
	with 13857 stored elements in Compressed Sparse Row format>

In [16]:
mnb = MultinomialNB()

In [17]:
#change y_train to integer data type
y_train=y_train.astype('int')
print(y_train)

5315    1
2082    1
1072    0
1296    1
472     1
       ..
3671    1
709     0
2487    1
174     1
1146    0
Name: Status, Length: 4459, dtype: int32


In [18]:
mnb.fit(x_traincv,y_train)

MultinomialNB()

In [19]:
#testmessage=x_test.iloc[0]
#MAKING PREDICTIONS TO INPUT TEST DATA
predictions=mnb.predict(x_testcv)

In [20]:
predictions

array([0, 1, 1, ..., 1, 0, 1])

In [21]:
#SHOW THE OUTPUT TEST DATA
a=np.array(y_test)

In [22]:
a

array([0, 1, 1, ..., 1, 0, 1], dtype=object)

In [23]:
count = 0
for i in range (len(predictions)):
    if predictions[i]==a[i]:
        count=count+1
print("prediction accuracy is " + str(count/len(predictions)))

prediction accuracy is 0.9829596412556054
